# Generated by Django 4.2 on 2023-06-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zahrweb', '0003_volunteer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='field_of_volunteers',
            field=models.CharField(choices=[('Computer', 'Computer'), ('Projects', 'Projects'), ('Education', 'Education')], help_text='type or field of voulnteer'),
        ),
    ]
