# Generated by Django 4.2 on 2023-06-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zahrweb', '0004_alter_volunteer_field_of_volunteers'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='Image',
            field=models.ImageField(default='default_image.jpg', help_text='Image Poster for news ', upload_to='static/'),
        ),
    ]
